### ISSUE TITLE
Update time allowed on Practice QT

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/website#2]
## Background
The time per question has been increased to 2.5 minutes, hence the practice QT on the website needs to be updated.

## Feature(s) Description
- [x] Increase the time allowed for CAT to 12.5 mins (each has 5 questions)
- [x] Increase the time allowed for SQT to 12.5 mins (each has 5 questions)
- [x] Update the instructions on each test to 'You have 12.5 minutes to complete this test.'

## User Testing Steps
Internal testing only

## Feature Champion
Nick

**Comment by nickaddy** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/website/2?planning-poker) with Zenhub @HalcyonJAC

**Comment by HalcyonJAC** [comment]
Sean Cuddihy has confirmed that it's working. I have released it to live.
